#!/usr/bin/env bash

# Install native apps
run_apps() {
    # utils
    brew cask install alfred
    brew cask install cakebrew
    brew cask install default-folder-x
    brew cask install dropbox
    brew cask install firefox
    brew cask install google-chrome
    brew cask install istat-menus
    brew cask install launchcontrol
    brew cask install moom
    brew cask install skype
    brew cask install slack
    brew cask install soulver
    brew cask install spectacle
    brew cask install spotify
    brew cask install the-unarchiver
    brew cask install transmission
    brew cask install vlc

    # dev
    brew cask install atom
    brew cask install bettertouchtool
    brew cask install bitbar
    brew cask install coderunner
    brew cask install couleurs
    brew cask install cyberduck
    brew cask install github
    brew cask install google-chrome-canary
    brew cask install hyper
    brew cask install imageoptim
    brew cask install iterm2
    brew cask install jewelrybox
    brew cask install ksdiff # Kaleidoscope command line
    brew cask install macdown
    brew cask install mongodb-compass
    brew cask install phpstorm
    brew cask install poedit
    brew cask install robo-3t
    brew cask install sequel-pro
    brew cask install vagrant
    brew cask install virtualbox
    brew cask install visual-studio-code
    brew cask install webstorm

    # colorpickers
    brew cask install colorpicker-skalacolor colorpicker-propicker
}
